/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CargoRouteImport } from './routes/cargo'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as ExpeditionRouteImport } from './routes/expedition'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as PersonnelRouteImport } from './routes/personnel'
import { Route as Station3dRouteImport } from './routes/station-3d'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoRoute = CargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionRoute = ExpeditionRouteImport.update({
  id: '/expedition',
  path: '/expedition',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelRoute = PersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const Station3dRoute = Station3dRouteImport.update({
  id: '/station-3d',
  path: '/station-3d',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cargo': typeof CargoRoute
  '/emergency': typeof EmergencyRoute
  '/expedition': typeof ExpeditionRoute
  '/inventory': typeof InventoryRoute
  '/personnel': typeof PersonnelRoute
  '/station-3d': typeof Station3dRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cargo': typeof CargoRoute
  '/emergency': typeof EmergencyRoute
  '/expedition': typeof ExpeditionRoute
  '/inventory': typeof InventoryRoute
  '/personnel': typeof PersonnelRoute
  '/station-3d': typeof Station3dRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cargo': typeof CargoRoute
  '/emergency': typeof EmergencyRoute
  '/expedition': typeof ExpeditionRoute
  '/inventory': typeof InventoryRoute
  '/personnel': typeof PersonnelRoute
  '/station-3d': typeof Station3dRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cargo'
    | '/emergency'
    | '/expedition'
    | '/inventory'
    | '/personnel'
    | '/station-3d'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cargo'
    | '/emergency'
    | '/expedition'
    | '/inventory'
    | '/personnel'
    | '/station-3d'
  id:
    | '__root__'
    | '/'
    | '/cargo'
    | '/emergency'
    | '/expedition'
    | '/inventory'
    | '/personnel'
    | '/station-3d'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CargoRoute: typeof CargoRoute
  EmergencyRoute: typeof EmergencyRoute
  ExpeditionRoute: typeof ExpeditionRoute
  InventoryRoute: typeof InventoryRoute
  PersonnelRoute: typeof PersonnelRoute
  Station3dRoute: typeof Station3dRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo': {
      id: '/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof CargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedition': {
      id: '/expedition'
      path: '/expedition'
      fullPath: '/expedition'
      preLoaderRoute: typeof ExpeditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel': {
      id: '/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof PersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station-3d': {
      id: '/station-3d'
      path: '/station-3d'
      fullPath: '/station-3d'
      preLoaderRoute: typeof Station3dRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CargoRoute: CargoRoute,
  EmergencyRoute: EmergencyRoute,
  ExpeditionRoute: ExpeditionRoute,
  InventoryRoute: InventoryRoute,
  PersonnelRoute: PersonnelRoute,
  Station3dRoute: Station3dRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
